#!/usr/bin/env bash

local_java_version=

if [ -f ".java-version" ]; then
  local_java_version=$(cat .java-version)
fi

rdir="jmh-result"
sbt="sbt -Djline.terminal=jline.UnsupportedTerminal"
jmh="jmh:run -prof gc -rf json"

for jdk_ver in "1.8" "11" "graalvm-ce-1.0.0-rc9"; do
for scala_ver in "2.12.7" "2.13.0-M5"; do
  jenv local "${jdk_ver}"
  java -version
  prefix="$rdir/$jdk_ver-$scala_ver"
  ${sbt} ++${scala_ver}! clean "${jmh} -rff ${prefix}.json -o ${prefix}.txt"
done
done

if [[ "${local_java_version}" != "" ]]; then
  echo "${local_java_version}" > .java-version
else
  rm .java-version
fi
